### ISSUE TITLE
[www.]darvin.dev can't be visited

### ISSUE THREAD

**Issue by valioDOTch** [unic/darvin-boilerplate#15]
Darvin.dev who is mentionned as the documentation source in Readme.md can't be reached at the moment.

![image](https://user-images.githubusercontent.com/800467/135836096-02b6ac3e-272e-4561-a9eb-f4de3de737cd.png)

If I try to visit the HTTP version, I end up with a "GoDaddy parked domain" page.

Also there's no HTTPS setup (which creates issues for Chrome e.g.).

**Comment by tobiasfrei** [comment]
I will try to bring it up again in the next 24h

**Comment by tobiasfrei** [comment]
You should be able to get informations here until the doc is up again.
http://web.archive.org/web/20210301182825/http://darvin.dev/

Thank you for reporting

**Comment by tobiasfrei** [comment]
darvin.dev is online and codebase updated to v3.0 with webpack 5 and latest dependencies.
